// <auto-generated/>
using System.IO;

namespace Fenton.TeamServices.BuildRestApi
{
    public class Churn
    {
        public string ItemName { get; set; }

        public int Count { get; set; }

        public int Score { get; set; }

        public string DisplayName
        {
            get
            {
                return Path.GetFileName(ItemName);
            }
        }
    }
}