// <auto-generated/>
using System.IO;

namespace Fenton.TeamServices.BuildRestApi
{
    public class FileChurn
    {
        public string ItemName { get; set; }

        public int Count { get; set; }

        public int Score { get; set; }

        public int Percentile { get; set; }

        public string DisplayName
        {
            get
            {
                return Path.GetFileName(ItemName);
            }
        }

        public string FolderName
        {
            get
            {
                return ItemName.Substring(0, ItemName.Length - DisplayName.Length);
            }
        }
    }
}