// <auto-generated/>
using System.IO;

namespace Fenton.TeamServices.BuildRestApi
{
    public class FolderChurn
    {
        public string ItemName { get; set; }

        public int Count { get; set; }

        public int Score { get; set; }

        public int Percentile { get; set; }

        public string DisplayName
        {
            get
            {
                return ItemName;
            }
        }
    }
}