// <auto-generated/>
namespace Fenton.TeamServices.BuildRestApi
{
    using System;
    using System.Collections.Generic;

    public class ChurnHistory
    {
        public DateTime StartOfWeek { get; set; }

        public string ItemName { get; set; }

        public int ChangeCount { get; set; }
    }
}