// <auto-generated/>
using System;
using System.Collections.Generic;

namespace Fenton.Forensics.TeamServices
{
    public class Changesets
    {
        public int count { get; set; }
        public List<Changeset> value { get; set; }
    }

    public class Changeset
    {
        public int changesetId { get; set; }
        public string url { get; set; }
        public Author author { get; set; }
        public CheckedInBy checkedInBy { get; set; }
        public string createdDate { get; set; }
        public string comment { get; set; }
        public bool? commentTruncated { get; set; }
    }

    public class Author
    {
        public string id { get; set; }
        public string displayName { get; set; }
        public string uniqueName { get; set; }
        public string url { get; set; }
        public string imageUrl { get; set; }
    }

    public class CheckedInBy
    {
        public string id { get; set; }
        public string displayName { get; set; }
        public string uniqueName { get; set; }
        public string url { get; set; }
        public string imageUrl { get; set; }
    }
}