// <auto-generated/>
using System.Collections.Generic;

namespace Fenton.Forensics.TeamServices
{
    public class Changes
    {
        public int count { get; set; }
        public List<Change> value { get; set; }
    }

    public class Change
    {
        public ChangedItem item { get; set; }
        public string changeType { get; set; }
    }

    public class ChangedItem
    {
        public int version { get; set; }
        public string path { get; set; }
        public string url { get; set; }
    }
}